---
abstract: 'Install missing modules explicitly'
author:
  - 'Michael F. Covington, <mfcovington@gmail.com>'
build_requires:
  Capture::Tiny: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4206, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-PrereqInstaller
provides:
  Perl::PrereqInstaller:
    file: lib/Perl/PrereqInstaller.pm
    version: v0.6.0
recommends:
  Pod::Markdown: '0'
requires:
  App::cpanminus: '0'
  Carp: '0'
  Cwd: '0'
  File::Basename: '0'
  File::Find: '0'
  Getopt::Long: '0'
  Perl::PrereqScanner: '0'
  Text::Wrap: '0'
  perl: '5.006'
resources:
  license: http://dev.perl.org/licenses/
version: v0.6.0
