#! perl
use strict;
use warnings;
use Module::Extract::Install;

my @files = @ARGV;

die "cpanm-missing requires at least one argument (a Perl script/module)\n"
    if scalar @files == 0;

my $installer = Module::Extract::Install->new;
$installer->check_modules(@files);

my @missing = $installer->not_installed;

if ( scalar @missing > 0 ) {
    print "\n";
    print "Modules to install:\n";
    print "  $_\n" for @missing;
    print "\n";

    $installer->cpanm;
    print "\n";

    print "Successfully installed:\n";
    print "  $_\n" for $installer->newly_installed;
    print "\n";

    print "Failed to install:\n";
    print "  $_\n" for $installer->failed_install;
    print "\n";
}
else {
    print "No missing modules need to be installed!\n";
}

exit;
